###1. Importing NumPy



In [14]:
#NumPy Import
import numpy as np
import pandas as pd

#1d array
arr_1d = np.array([1,2,3,4,5])
print("2D array: \n",arr_1d)

print(arr_1d[0])

#2d array
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: \n",arr_2d)

2D array: 
 [1 2 3 4 5]
1
2D array: 
 [[1 2 3]
 [4 5 6]]


###2. Basic Array Operations

In [15]:
#Element Wise operations
arr_sum = arr_1d + 5
print("Element Wise addition \n",arr_sum)

#Difference
arr_diff = arr_1d - 2
print("Difference: \n",arr_diff)


Element Wise addition 
 [ 6  7  8  9 10]
Difference: 
 [-1  0  1  2  3]


###3. Reshaping and Transposing Array


In [16]:
#Reshape 1D to a 2D array
reshaped_ar= arr_1d.reshape(5,1)
print("Reshaped array: \n",reshaped_ar)

#Transpose
transposed_ar = arr_2d.transpose()
print("Transposed array: \n",transposed_ar)

#Array Indexing and slicing
print("\nFirst element of 1D array: ",arr_1d[0])
print("\nSecond Row of 2D array: ",arr_2d[1,:])

Reshaped array: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
Transposed array: 
 [[1 4]
 [2 5]
 [3 6]]

First element of 1D array:  1

Second Row of 2D array:  [4 5 6]


###4. Activity


*   Create 3x3 array with values ranging from 1-9
*   Find the sum, mean and, standard deviation of the array
*   Extract the Subarray that consist of the first two rows and column



In [17]:
#3x3 array
arr_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3x3 array: \n",arr_3x3)

#sum of 3x3 array
print("\nSum of 3x3 array: ",np.sum(arr_3x3))

#mean
print("\nMean of 3x3 array: ",np.mean(arr_3x3))

#standard deviation
print("\nStandard deviation of 3x3 array: ",np.std(arr_3x3))

#subarray
print("\nSubarray: \n",arr_3x3[:2,:2])



3x3 array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of 3x3 array:  45

Mean of 3x3 array:  5.0

Standard deviation of 3x3 array:  2.581988897471611

Subarray: 
 [[1 2]
 [4 5]]


###Pandas Practice


In [22]:
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df

df2 = pd.DataFrame({'A': [1, 3], 'B': [2, 4]})
df2


A  B
0  1  2
1  3  4

In [26]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 27, 22], 'Salary': [70000, 80000, 60000]}
df = pd.DataFrame(data)
df[['Salary']]

Salary
0   70000
1   80000
2   60000

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)
print(result)

32
